### ISSUE TITLE
Pa11y execution 

### ISSUE THREAD

**Issue by vanatomas** [nature/pa11y#100]
Hi, is there a way to check if tests run daily? Also, if possible to change time to run tests weekly?

**Comment by rowanmanning** [comment]
Hi @vanatomas, is this regarding pa11y itself or the web-based dashboard?

**Comment by vanatomas** [comment]
Hi, regarding web dashboard if both are differentl.

**Comment by rowanmanning** [comment]
Ah cool. Yes they're different projects. This repo is for the command-line tool, sorry for confusion. I've opened a new issue where I can answer :) https://github.com/nature/pa11y-dashboard/issues/86

**Comment by vanatomas** [comment]
Hello, would you be able to respond on this one:

Authenticated editors? #87
