### ISSUE TITLE
Error: HeadlessError: Error executing command to extract phantom ports

### ISSUE THREAD

**Issue by andrewholgate** [nature/pa11y#103]
Using `3.0.0` and `3.0.1` (but not `2.4.4`) I receive the below error.

It appears to be caused by the upgrade from truffler [`1.0`](https://github.com/nature/pa11y/blob/2.4.4/package.json#L34) to [`2.0`](https://github.com/nature/pa11y/blob/2.4.4/package.json#L34). 

```
$ node_modules/.bin/pa11y --standard WCAG2A --ignore 'notice;warning' file:files/a11y_audit/sitemap-4.html
Welcome to Pa11y

 > Error: HeadlessError: Error executing command to extract phantom ports: Error: Command failed: /bin/sh -c if which ss > /dev/null; then ss -nlp | grep "[,=]7509,"; else netstat -nlp | grep "[[:space:]]7509/"; fi

    at /var/www/project/node-a11y-auditor/node_modules/pa11y/node_modules/truffler/node_modules/node-phantom-simple/node-phantom-simple.js:256:22
    at ChildProcess.exithandler (child_process.js:210:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by rowanmanning** [comment]
Hmm, I haven't come across this before! Could I get a bit of information about your system? The following would be really useful, so I can try to replicate it:

- OS name/version
- Node.js version
- PhantomJS version

**Comment by andrewholgate** [comment]
I did some more debugging on this issue and it is unrelated to pa11y.

It appears to be very similiar to issue baudehlo/node-phantom-simple#76, which the proposed fix does not work in my case. It's very specific, running a Ubuntu host with a Docker container. 2 colleagues running Mac hosts were unable to replicate.

**Comment by limestreet** [comment]
I think I have the same issue (`Error: HeadlessError: Error executing command to extract phantom ports`) with ubuntu 14.04 64 bit docker container on Shippable. On localhost (ubuntu 14.04 64 bit in docker/outside docker) it's working like a charm.
I found very similar issue (but related to uncss) mentioned on Shippable issue tracker: https://github.com/Shippable/support/issues/884 and it's probably because of AppArmor
P.S. I tested with nodejs 0.10.25 and latest 0.12.x - don't remember exact version and latest phantomjs (2.1.3)

**Comment by RobLoach** [comment]
Installing `net-tools` does not fix the issue, unfortunately. Running the same as @limestreet above.

**Comment by limestreet** [comment]
I resolved problem by installing newest Phantomjs (2.1.1 - from their page) following this tutorial: https://gist.github.com/julionc/7476620 (I only changed version to latest one)
And then pa11y (from npm). Now all is working like a charm :)

**Comment by RobLoach** [comment]
[phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt) comes with `2.1.1`, which was still problematic for me last time I tested. `npm i phantomjs-prebuilt -g`

Could be installing it wrong. Will have another test with the latest updates.
