### ISSUE TITLE
pa11y 3 does not work with a lot of pages any more

### ISSUE THREAD

**Issue by joscha** [nature/pa11y#104]
Pa11y 3 uses Truffler 2 - Truffler 2 creates a new Phantom instance for each call to `.run` - when testing a lot of pages with pa11y at the same time, this means that the OS runs out of handles for the forked phantom. This basically renders pa11y 3 unusable for larger websites currently.

The error you get looks like this:
```console
/Users/jfeth/dev/pa11y-crawler/node_modules/node-phantom-simple/node-phantom-simple.js:148
    phantom.stderr.on('data', function (data) {
                  ^

TypeError: Cannot read property 'on' of undefined
    at spawnPhantom (/Users/jfeth/dev/pa11y-crawler/node_modules/node-phantom-simple/node-phantom-simple.js:148:19)
    at Object.exports.create (/Users/jfeth/dev/pa11y-crawler/node_modules/node-phantom-simple/node-phantom-simple.js:286:3)
    at /Users/jfeth/dev/pa11y-crawler/node_modules/pa11y/node_modules/truffler/lib/truffler.js:100:12
    at /Users/jfeth/dev/pa11y-crawler/node_modules/pa11y/node_modules/truffler/lib/truffler.js:77:4
    at /Users/jfeth/dev/pa11y-crawler/node_modules/async/lib/async.js:689:13
    at iterate (/Users/jfeth/dev/pa11y-crawler/node_modules/async/lib/async.js:265:13)
    at /Users/jfeth/dev/pa11y-crawler/node_modules/async/lib/async.js:277:29
    at /Users/jfeth/dev/pa11y-crawler/node_modules/async/lib/async.js:44:16
    at /Users/jfeth/dev/pa11y-crawler/node_modules/async/lib/async.js:694:17
    at /Users/jfeth/dev/pa11y-crawler/node_modules/async/lib/async.js:173:37
```

with your processes like this:
![activity_monitor__my_processes_](https://cloud.githubusercontent.com/assets/188038/11228794/6fcdf952-8de3-11e5-8fe7-370c89389787.png)

**Comment by rowanmanning** [comment]
Hi @joscha, I'm not sure if this is something that can be addressed in pa11y itself without another breaking API change. How is your web crawler working and how many pages does it try to crawl at once? Does it use pa11y as a library or the command-line tool?

Internally we do process a large number of pages, but we either do it in sequence or by using [async's queue method](https://github.com/caolan/async#queue) which supports specifying concurrency. This allows you to tweak the effectiveness of your script based on the hardware you're running on.

There's an [example series here](https://github.com/nature/pa11y/blob/master/example/multiple/index.js) and I've thrown together an example using `async.queue` below:

```js
var async = require('async');
var pa11y = require('pa11y');

var test = pa11y({
    log: {
        debug: console.log.bind(console),
        error: console.error.bind(console),
        info: console.log.bind(console)
    }
});

var CONCURRENCY = 4;

var queue = async.queue(function(task, done) {
    console.log('Processing task:', task.url);
    test.run(task.url, done);
}, CONCURRENCY);

queue.drain = function() {
    console.log('All tasks have been processed');
};

queue.push({url: 'http://nature.com/'}, function(error) {
    console.log('Finished processing Nature home');
});

queue.push({url: 'http://nature.com/nplants/'}, function(error) {
    console.log('Finished processing Nature Plants home');
});
```

**Comment by joscha** [comment]
It uses pa11y as a library. The network of pages is in the multiple hundreds. I changed my code into being run sequentially now, that works but is painfully slow as I also have a wait of 3s on the page. I might check out the async concurrency which seems to be a good fit as then I can tweak it accordingly as you say. Just generally: what was the reason to construct a new phantom instance for every run call? Was it because of session data or because you could influence a test being run by a later one if not being careful?

**Comment by rowanmanning** [comment]
A bit of both, but mostly because we were running into lots of issues with zombie processes which were at least partly related to long-running PhantomJS instances. Also the timeout logic was crazy complicated and a single timed out test could prevent later ones from running at all in certain situations.

I know it's not ideal to create a new instance for each call, but it allowed us to massively simplify and tidy up the codebase. Also the timeout logic is now much more solid, which means we see absolutely no zombie processes created. With pa11y 2.0, our dashboard server would fall over regularly because of a single timed out test orphaning PhantomJS processes and eating up all the memory.

Queue definitely seems like it might solve your problem :) it's interesting to hear about your experience with pa11y, we always like to hear how people are using it. Let me know if I can help in any other way!

**Comment by joscha** [comment]
Cool, thank you. I'll try async first, closing this for now.
