### ISSUE TITLE
json output ends early

### ISSUE THREAD

**Issue by mfairchild365** [nature/pa11y#112]
It looks like versions > 2.4.4 have issues with the JSON reporter. The majority of tests results in early termination of the JSON output. It doesn't seem to matter what pages I test against.

**Comment by rowanmanning** [comment]
Hmm, that's not good at all! I'll look into fixing it, thanks

**Comment by rowanmanning** [comment]
Steps to reproduce:

```
pa11y nature.com -r json
```

**Comment by rowanmanning** [comment]
OK I've fixed this and released pa11y `2.4.5` and `3.2.1`. Thanks for reporting, @mfairchild365. Can you confirm that it's working for you now?

**Comment by mfairchild365** [comment]
Yep, seems to be working. Thanks for the quick fix!
