### ISSUE TITLE
Testing a file instead of page ?

### ISSUE THREAD

**Issue by vsraptor** [nature/pa11y#117]
Is there a way to test a html FILE instead of web page ?

**Comment by rowanmanning** [comment]
Yes there is, you can use a URL with the "file" scheme. E.g.

```
pa11y file:///path/to/your/file.html
```

Let me know if that doesn't work for some reason :)

**Comment by rowanmanning** [comment]
(I'll get this added to the documentation for future reference too)

**Comment by vsraptor** [comment]
I seem to be getting timeout ...

 > PhantomJS browser created
Error: Truffler timed out (30000ms)
    at C:\...\npm\node_modules\pa11y\node_modules\truffler\lib\truffler.js:75:17
    at C:\...\npm\node_modules\pa11y\node_modules\async\lib\async.js:689:13

Otherwise accessing the file via local http-server, works OK.
