### ISSUE TITLE
Handling Logins ?

### ISSUE THREAD

**Issue by vsraptor** [nature/pa11y#118]
Where should I look to make changes if I need to add Login page support ?
Or is it already available ?!

thanks

**Comment by rowanmanning** [comment]
Hi @vsraptor, there currently isn't login support but we're working on it. There's an ongoing issue here: #98, and @GlynnPhillips has started working on it. We decided the best way to get around it would be to allow users to execute their own PhantomJS code before pa11y runs.

In the meantime it is possible to set cookies in pa11y, so you could potentially create a session cookie in your test environment.
