### ISSUE TITLE
pa11y return empty response after waiting for few seconds

### ISSUE THREAD

**Issue by softwareklinic** [nature/pa11y#125]
Keyurs-MacBook-Air:basic FamilyMac$ pa11y nature.com
Welcome to Pa11y

Keyurs-MacBook-Air:basic FamilyMac$ 

----------- can u help identify what could be the issue -----------------

**Comment by rowanmanning** [comment]
Hi @softwareklinic, could you run the following (pa11y in debug mode) and let me know the output?

```
pa11y --debug nature.com
```

**Comment by softwareklinic** [comment]
Ty - I figured it out - it was an issue
With not finding phantomjs.



Regards,
Keyur

On Feb 1, 2016, at 3:26 AM, Rowan Manning <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @softwareklinic<https://github.com/softwareklinic>, could you run the following (pa11y in debug mode) and let me know the output?

pa11y --debug nature.com<http://nature.com>

**Comment by rowanmanning** [comment]
Great. Thanks for letting me know
