### ISSUE TITLE
pa11y returns empty response with and without --debug

### ISSUE THREAD

**Issue by wrburgess** [nature/pa11y#126]
No matter what I've tried thus far, I run pa11y and get zero response.

## Environment

```
Mac 10.11.2
node v5.1.1
npm v3.5.2
pa11y@3.4.0
phantomjs2@2.0.2 
```

## Installation Steps

1. `npm install -g pa11y`
1. `npm install -g phantomjs2`
1. copied `/.npm-packages/lib/node_modules/phantomjs2/lib/phantom/bin/phantomjs.exe` to `/.npm-packages/lib/node_modules/npm/phantomjs.exe`

## Attempts

command: `pa11y nature.com`
response: `Welcome to Pa11y`

command: `pa11y nature.com --debug`
response: `Welcome to Pa11y`

command: `pa11y --reporter csv nature.com > report.csv`
response: `report.csv` is empty

**Comment by rowanmanning** [comment]
Hi @wrburgess, thanks for the detailed report! One part of your installation steps I don't quite understand is point 3. What does the copying do? It kind of looks like part of the Windows instructions (which means I need to clarify the docs).

One thing you could try is installing PhantomJS [through their site](http://phantomjs.org/) or using `brew` to install it.

If that fails, you could try pointing pa11y directly to your PhantomJS executable:

```
pa11y nature.com --phantomjs <path>
```

**Comment by wrburgess** [comment]
*What does the copying do? It kind of looks like part of the Windows instructions*

@rowanmanning Honestly, I didn't know, but I was trying everything I could do before posting an issue. I did realize that the instructions were for Windows, but I decided to give it a shot on Mac in case I was supposed to know that already.

**Comment by wrburgess** [comment]
BTW, this did the trick for me after installing with brew:

`pa11y nature.com --phantomjs /usr/local/bin/phantomjs`

**Comment by rowanmanning** [comment]
Ah cool, well if you make sure `/usr/local/bin` is in your `PATH` environment variable you should be able to use pa11y without the `--phantomjs` flag :)
