### ISSUE TITLE
Apply rulesets based on doctype

### ISSUE THREAD

**Issue by matthewmorek** [nature/pa11y#131]
There are several WCAG2 rules that do not apply to HTML5, such as:
```
WCAG2AA.Principle1.Guideline1_3.1_3_1.H73.3.NoSummary
```
Pa11y doesn't seem to be able to distinguish between HTML4.01 and HTML5, so it applies all the rules regardless of specified doctype.

Sure, you can ignore certain rules, but wouldn't it be nicer to just run:
```shell
$ pa11y --mode html5 http://example.com
```
That way we could be sure our documents will be checked only against rules that actually apply to a given doctype. Better yet, Pa11y could automatically detect doctype and apply default rulesets based on that info.

References:
- [WCAG20-TECHS/H73](https://www.w3.org/TR/WCAG20-TECHS/H73)
- [WAI • Tables: Caption & Summary](https://www.w3.org/WAI/tutorials/tables/caption-summary/)

**Comment by rowanmanning** [comment]
Hi @matthewmorek, thanks for the report. I agree it would be nice if pa11y was sensitive to the doctype, but we completely rely on [HTML CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) for the reporting of errors. I don't think it'd be maintainable for us to implement our own check of the doctype and exclude relevant rules.

There's already an issue open on HTML CodeSniffer which seems related https://github.com/squizlabs/HTML_CodeSniffer/issues/137 - It may be worth contributing to that thread :)
