### ISSUE TITLE
pa11y hard to use from non-internet connected machines

### ISSUE THREAD

**Issue by tomduckering** [nature/pa11y#44]
Hi,

Thanks for making pa11y. We're trying to use it for our project but since we have machines with no internet connectivity we have to jump through some hoops to make HTMLCS.js available to download via HTTP.

Is there a reason you're not just including this js file in your code or is there a reason it can't be fetched from a local file system?

Happy to try and make a fix but wanted to understand if there were some reasons for this not being possible.

Thanks,

Tom

**Comment by rowanmanning** [comment]
Marking this as resolved – you can achieve this from an offline machine in the way that @whymarrh specified for now. In the next version of pa11y, I'm considering moving to a locally-hosted version of HTML CodeSniffer by default which will make this much easier in future.
