### ISSUE TITLE
Zombies!

### ISSUE THREAD

**Issue by mfairchild365** [nature/pa11y#45]
First of all, thank you for such a wonderful project.  We have been using it quite extensively and have thus found some problems with it.  The most problematic of which is that it spawns zombie processes that consume memory and cpu and eventually crash the server.

Some details:
If you run pa11y on a page that generates an error, p11y eventually reaches its timeout but at least two processes live on (node and phantomjs).

To reproduce the error I have been able to do the following:
1) run `pa11y -r json http://prairieschooner.unl.edu/?q=fusion%2Fwork%2Fbus-driver` and wait for it to error
2) run `ps x -o  "%p %r %y %x %c "` or look at the output of `ps x` and you should see two zombies processes (one for `node` and one for `phantomjs`).  Sometimes you will see one or the other.

We are using [SiteMaster](https://github.com/unlsitemaster/site_master) to scan our sites with several metrics, including accessibility via pa11y.  In order to get around this problem, I implemented our own custom timeout for the pa11y process, which recursively kills child processes.  See: https://github.com/UNLSiteMaster/metric_pa11y/commit/d478bc8b914248b54fa36a49964b418b49888676

I'm not sure where exactly this problem lives.  It might actually be a bug in phantomjs.  I just thought I'd give you a heads up.

**Comment by mfairchild365** [comment]
@rowanmanning This is still an ongoing issue for us.  I'm curious if you have made any progress or if there is anything that I can do to help.

**Comment by rowanmanning** [comment]
Hi @mfairchild365, sorry for very slack replies lately. I've managed to block out a day (today) to work on this, will feed back if I work something out or get stuck. If I don't get anywhere in the next hour or so I'll try implementing a short-term fix which kills any zombie processes before node exits.

**Comment by rowanmanning** [comment]
Holy shit I think I found a fix! Fresh eyes I guess. Basically the messages that come back from HTML Codesniiffer contain a DOM element, this obviously eats up loads of memory and I think in the case of this specific page (and others) there must be an infinite loop or something like that. I'm removing the DOM element *before* sending data back to node locally, and it's working. PR incoming, would be great if you can test it out.

I'd still like to investigate what exactly it is about the page in question, but that can come later today.

**Comment by rowanmanning** [comment]
Closing, fixed in #63
