### ISSUE TITLE
Sync JSON config file with command line options

### ISSUE THREAD

**Issue by whymarrh** [nature/pa11y#58]
Idea: adding the ability to configure all the same options in the JSON config (`.pa11yrc`) that are available as command line flags.

I'm not 100% sure where I would draw the line on this as not _all_ of the command line flags are worthy (e.g. help and version), but I think the others might be useful.

Thoughts? With ideas like #50/#51 and #53, maybe the JSON config is underutilised.

**Comment by rowanmanning** [comment]
Just a note, this has made it into a development version of pa11y, support for configuring any PhantomJS flag. There's no ETA yet but I'll keep you posted.

**Comment by rowanmanning** [comment]
@whymarrh can this issue close based on the new 2.0 API (where you can configure everything from the JSON config if you need to)?

**Comment by whymarrh** [comment]
Sure can!
