### ISSUE TITLE
Source code and screenshot backup

### ISSUE THREAD

**Issue by paipai** [nature/pa11y#60]
Hello,
For some website, the page tested by pa11y is not the same as the one displayed in a browser (maybe cause of the user-agent ...). It would be nice to have an option to get a backup of the source page code and a screenshot (phantomjs) of the page tested by pa11y to be sure this is the good one.

**Comment by rowanmanning** [comment]
Hi @paipai, how would you envisage this working? I like the idea. In the meantime, I'd suggest requesting the page via cURL with the pa11y user-agent (pa11y/x.x.x) to test whether it's the correct version of the page being accessed.

**Comment by paipai** [comment]
Is there any chance to save source page code from phantomjs in an HTML file ?

**Comment by rowanmanning** [comment]
Yes, possibly. I'll have a think about if there's a nice way to do this. It could potentially be a different reporter.

**Comment by rowanmanning** [comment]
This is unlikely to ever make it into pa11y. For future reference the suggested solution if you wish to do this is as follows:

1. Use cURL to save a page locally to an HTML file:
    
    ```
    curl http://www.nature.com/ > nature-home.html
    ```

2. Run pa11y on the local file:

    ```
    pa11y file://path/to/nature-home.html
    ```

3. Take a screen-shot with a tool of your choosing:

    ```
    webkit2png file://path/to/nature-home.html -o nature-home.png
    ```

**Comment by paipai** [comment]
Thanks for the workaround.
