### ISSUE TITLE
Default to TLSv1 in order to support older versions of PhantomJS

### ISSUE THREAD

**Issue by whymarrh** [nature/pa11y#62]
PhantomJS previously (`<= 1.9.7`) used SSLv3 for all secure connections and since a lot of servers are disabling it due to the :poodle: attack, the `--ssl-protocol=tlsv1` flag would need to be used to change the default behaviour.

PhantomJS 1.9.8 (released 5 days ago) changed the default protocol to TLSv1, fixing the issue.

This is more of a question: should the `--ssl-protocol=tlsv1` flag be passed by default in order to support older versions  of PhantomJS? The alternative would be to require a newer PhantomJS binary (`>= 1.9.8`) when the server doesn't support SSLv3.

**Comment by rowanmanning** [comment]
Sorry for the (very) late response on this. Maybe, yes, I'm trying to think if there are any downsides to using tlsv1 by default. If this is something you want to work on, I'll accept a PR. Otherwise I can pop on my to-do list

**Comment by whymarrh** [comment]
No worries (says a late response to a late response). It can definitely sit on the to-do list, especially since PhantomJS 1.9.8 has been released with a fix. I do want to submit a PR* though, as I think this, #55, #58, and #64 are all kind of related.

\* Though #55 might cover it already.

**Comment by rowanmanning** [comment]
As I'm working on a `2.0` breaking version, it makes sense to bring this into it.

**Comment by rowanmanning** [comment]
Added to pa11y 2.0 in 62f3a19cc6f7d04f302ab8094ac7eca3db2bf452
