### ISSUE TITLE
Confirming usage under the GPL

### ISSUE THREAD

**Issue by benbalter** [nature/pa11y#65]
Greetings team pa11y! @adelevie introduce me to the awesomeness that is pa11y last week, and since then, we've set out to make an automated 508 testing tool for Jekyll and other static sites. We've lovingly called the Ruby gem [Ra11y](https://github.com/benbalter/ra11y).

Before we go too far down the :rabbit: hole, we wanted to check in with you and make sure that we were honoring both the project's vision and the spirit of the GPL. 

Pa11y is not distributed with Ra11y, instead, the Readme instructs users on how to install Pa11y via NPM. Ra11y shells out to pa11y with default arguments, and then parses the JSON returned via stdout. The executable is even configurable if the user would like to use a different command-line testing tool.

From [The GPL FAQ](https://www.gnu.org/licenses/gpl-faq.html#MereAggregation):

> By contrast, pipes, sockets and command-line arguments are communication mechanisms normally used between two separate programs. So when they are used for communication, the modules normally are separate programs.

To me, it sounds like the letter of the law is clear, but because we'll likely want to contribute improvements upstream, wanted to check in with the project maintainers personally before we were too far along.

**Edit**: To answer the most obvious question ("why not just use pa11y?"), Ra11y serves as an test abstraction, allowing you run to run accessibility tests against an entire directory of static files locally, aggregating the results.

**Comment by dotcode** [comment]
Hi @benbalter! Thanks for getting in touch, we're honoured.

Ra11y sounds neat, complies with both the letter of the law (and most definitely our vision), so we're looking forward to some pull requests, let's see where we go.

Nice name as well ;)

**Comment by adelevie** [comment]
Woo! Thanks, @dotcode! At [18F](https://18f.gsa.gov), we're working hard to improve web accessibility for the US federal government, and pa11y looks like it will play an important role. Thanks again for building this tool and being clear about licensing :)

**Comment by dotcode** [comment]
No problem, glad to help (as is @rowanmanning, who actually did all the work ;)
