### ISSUE TITLE
Don't use return codes to indicate lint error count

### ISSUE THREAD

**Issue by whymarrh** [nature/pa11y#69]
I feel a bit guilty about this one, since I introduced it in #25 and #32.

I still think the process should exit with an error to indicate that there were errors (as per #14), but using the actual count as the code will break if there are too many errors ([more than 255](http://stackoverflow.com/a/5149245)). Also, using -1 wraps around, and while it is still *possible* to get it back, the process is a hassle (not to mention that if there are exactly 255 errors, the results count will be indistinguishable from a pa11y internal error).

Thoughts on this?

**Comment by whymarrh** [comment]
I've been using this functionality to great success, but admittedly with a small number of errors. In thinking through #68 I realized that 255 errors would be the same as an internal error and that 256 wraps back around to 0.

**Comment by rowanmanning** [comment]
Hmm, OK. Yeah we should probably fix this but it's technically a breaking change. Possibly the solution is to add a new cli reporter that exits with 1 or 0?

**Comment by whymarrh** [comment]
You're right about it being a breaking change. The strict flag wouldn't make sense anymore as well.

I hadn't thought about a new reporter, would it be the default? There might be other reporters that this functionality could be rolled into (e.g. [18F/pa11y-reporter-ci](https://github.com/18F/pa11y-reporter-ci)). I think the possible issue here is that 256 errors will still wrap back around to a successful run by default.

As for the return codes themselves: I think that there should be three exit codes to represent the three states:

**0**: Successful run with no lint errors
**1**: Successful run with lint errors
**2**: Internal error while running tests

**Comment by rowanmanning** [comment]
It depends. We could add a cli-strict reporter in the short-term which is not default, and mention in the README. It would be nicer to bring this work into pa11y 2.0. As an aside, I've been thinking about 2.0 and it might just be an overhaul of the current codebase (phantomjs and HTML CodeSniffer still there) rather than a full rewrite – the scope of building our own version of CodeSniffer is pretty huge

**Comment by mfairchild365** [comment]
forgive me if I am being ignorant, but could a solution be to add a configuration option?  something like `--exit-bool` or `--use-standard-exit-code`?  It seems a little overkill to make an entirely separate reporter.

**Comment by whymarrh** [comment]
@mfairchild365 you are absolutely correct in that a flag could be added. I guess it comes down to what should be the default.

**Comment by rowanmanning** [comment]
I can't remember off the top of my head, but it may not be super simple to read flags in the reporters. I'll investigate, but yes that might be the nicest solution @mfairchild365 :)

**Comment by rowanmanning** [comment]
Fixed in 2.0
