### ISSUE TITLE
Review Truffler

### ISSUE THREAD

**Issue by rowanmanning** [nature/pa11y#73]
Hey @whymarrh, I've been working on splitting out the PhantomJS part of pa11y into a separate library, which is now open-sourced at https://github.com/nature/truffler. Before I start using this, can you envisage any issues? Is there anything I've missed?

There's no rush on this, but it'd be excellent if you could cast your eyes over it at some point.

**Comment by whymarrh** [comment]
Awesome work @rowanmanning!

From the looks of it, Truffler solves a number of the issues that pa11y has run into: multiple tests, dealing with PhantomJS flags, etc. Two quick notes (I'm not sure if they're better discussed here or in the Truffler repo):

- Is there an alternative to [sgentle/phantomjs-node](https://github.com/sgentle/phantomjs-node)

    I would need to look into it more, but is there a different PhantomJS bridge that doesn't [work the way that one does](https://github.com/sgentle/phantomjs-node/blob/120559bb051578f07316d5ee552fc702a1885073/README.markdown#no-really-how-does-it-work)? I can think of a few weaknesses of that particular module, namely:

    - It's a pain to install on Windows
    - The way it works is, er, not great

        More zombies?

            4146 ttys000    0:03.16 phantomjs /tmp/node_modules/truffler/node_modules/phantom/shim.js 12300 127.0.0.1
            4187 ttys000    0:02.02 phantomjs /tmp/node_modules/truffler/node_modules/phantom/shim.js 12300 127.0.0.1
            4200 ttys000    0:03.17 phantomjs /tmp/node_modules/truffler/node_modules/phantom/shim.js 12300 127.0.0.1

        That is `ps | grep [p]hantomjs` after running a test script that crashed three times (due to syntax/parse errors in the script).

- Is there a "built-in" way to run multiple tests

    I am probably just missing something here, but I brought in [async](https://github.com/caolan/async) to run multiple tests before calling the `exit` method. Is that the expected way? On that note, it might be useful to add another example to repo, one with multiple tests.

**Comment by whymarrh** [comment]
This is what I had for multiple tests:

```js
var async = require("async");
var truffler = require("truffler");

truffler({
    testFunction: function (browser, page, done) {
        page.evaluate(function () {
            return document.title;
        }, function (result) {
            done(null, result);
        });
    }
}, function (err, test, exit) {
    var tests = [
        function (next) {
            test("http://www.wikipedia.org/", function (err, results) {
                if (err) {
                    console.error(err);
                    return next(err);
                }
                console.log(results);
                return next();
            });
        },
        function (next) {
            test("https://www.npmjs.com/", function (err, results) {
                if (err) {
                    console.error(err);
                    return next(err);
                }
                console.log(results);
                return next();
            });
        }
    ];
    async.series(tests, function (err, results) {
        exit();
    });
});
```

For the crashing script, remove the `s` from `results` on the tenth line from the bottom.

**Comment by paipai** [comment]
Well done. I was wondering how to make multiples tests too

**Comment by rowanmanning** [comment]
Hi Whymarrh,

Thanks for taking a look, your feedback's really helpful. So firstly:

> Is there an alternative to sgentle/phantomjs-node

Not that I've found; PhantomJS isn't built in Node.js and so runs as a completely separate process. There's not really a nicer way to communicate between Node.js and PhantomJS's JavaScript environments unfortunately. Also this is the library that has been used in pa11y since the start, it's not great that there are still zombies, but they can be reduced with some good error handling in a test script.

> Is there a "built-in" way to run multiple tests

No, but there can be. Your implementation is *exactly* what I had in mind, but I'm considering adding a method on the test function which does this (probably in a version down the line). Something like:

```js
truffler({}, function (err, test, exit) {
    test.multiple([
            'http://www.wikipedia.org/',
            'https://www.npmjs.com/'
        ], function (error, results) {
        // ...
        exit();
    });
});
```

**Comment by rowanmanning** [comment]
Example of testing multiple URLs added: https://github.com/nature/truffler/commit/ea364a9d8c89c508dba88610929d82321df7dbad

**Comment by whymarrh** [comment]
+1 for the adding the example, thanks!

Just on the PhantomJS bridge: yup, you'd still need a bridge, but I do think that there are nicer ways to interact with the process. I've opened up nature/truffler#2 to follow up on the PhantomJS bit, outside of that though, I don't think I have much more feedback. Truffler looks great!
