### ISSUE TITLE
Allow for reporting levels to be set: error, warning, notice

### ISSUE THREAD

**Issue by andrewholgate** [nature/pa11y#74]
Great tool, very good implementation of HTML Code Sniffer!

For CI integration, it would be very useful to be able to specify the reporting level, eg.
```
0 - error & warning & notice
1 - error & warning
2 - error
```
With 0 being the default.

In our case, this would allow CI testing to halt a build if an `error` is found in the WCAG standard but allow the build to continue if only warnings and notices are present.

**Comment by rowanmanning** [comment]
Hi @andrewholgate, this has made it into pa11y 2.0 which is due to be released soon. You can [read up here](https://github.com/nature/pa11y/blob/2.x/README.md#exit-codes). Does this suit your needs?

**Comment by andrewholgate** [comment]
Perfect, the configurable `--level` flag will fit my use-case perfectly. Thanks!

A working link for the README should be: https://github.com/nature/pa11y/blob/2.0.0/README.md

**Comment by andrewholgate** [comment]
I just installed and used v2.1.0, very impressive! Thanks for your great work.
