### ISSUE TITLE
Review Pa11y 2.0 API

### ISSUE THREAD

**Issue by rowanmanning** [nature/pa11y#76]
A first pass of pa11y 2.0 has been built, and is viewable on the [2.x branch for now](https://github.com/nature/pa11y/tree/2.x). It's had a couple of big API changes, and the code itself is a ground-up rewrite.

I decided to stick with PhantomJS and HTML CodeSniffer for this release, if we ever move away from them it'll be much further down the line. The core library has been split into a few smaller modules and is a lot cleaner and easier to understand than 1.0; also a lot of attention has been given to the documentation.

I'd like to get feedback on the API changes which are significant (hence the 2.0 bump) before this gets released so that we can make changes if needed. @dotcode, @whymarrh, @stephenmathieson – it'd be much appreciated if you had time to review (the API more than the code itself).

The [2.x README](https://github.com/nature/pa11y/blob/2.x/README.md) is pretty comprehensive, and I've also written a [Migration Guide](https://github.com/nature/pa11y/blob/2.x/MIGRATION.md) to highlight the changes and help people make the switch.

Thank you

**Comment by whymarrh** [comment]
This looks to be a solid 2.0.

A few quick notes:

- The [first example in the README][1] shows the following, which is missing the `exit` parameter:

```js
var pa11y = require('pa11y');
pa11y(options, function (error, test) {
    test('nature.com', function (error, results) {
        /* ... */
    });
});
```

- [The section on exit codes][2] in the README states:

> - `none`: never exit

I think that should read "always exist with zero".

(A specific +1 for the migration guide, that's well thought out.)

  [1]:https://github.com/nature/pa11y/blob/e9ec2cefde11da12026c9d247897021079e05e85/README.md#pa11y
  [2]:https://github.com/nature/pa11y/blob/e9ec2cefde11da12026c9d247897021079e05e85/README.md#exit-codes

**Comment by rowanmanning** [comment]
Thanks for the feedback :) I've updated the README to clarify the `--levels` argument and added the `exit` parameter to the first example.

I'll get this released soonish then, once I've gathered feedback within Nature.
