### ISSUE TITLE
Add functionality to abort requests for adverts

### ISSUE THREAD

**Issue by GlynnPhillips** [nature/pa11y#85]
It would be nice if Pa11y had an option to enable adblocking to prevent poor advert code showing in your reports.

I think this might be possible with the [onResourceRequested!](http://phantomjs.org/api/webpage/handler/on-resource-requested.html) method in PhantomJS

**Comment by rowanmanning** [comment]
I think we should cover this feature with #108, which would allow users to hide/ignore adverts. Happy to close, @GlynnPhillips?

**Comment by GlynnPhillips** [comment]
Yeah, agree.
