### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by nford** [nature/pa11y#86]
How to use Pa11y from behind a proxy?

**Comment by rowanmanning** [comment]
High @nford, you should be able to pass in PhantomJS [command-line parameters](http://phantomjs.org/api/command-line.html) in the config.

If you're using the command-line interface you'll need to create a JSON config file like this:

```json
{
    "phantom": {
        "parameters": {
            "proxy": "1.2.3.4:8080",
            "proxy-type": "http|socks5|none",
            "proxy-auth": "username:password"
        }
    }
}
```

Then run pa11y, pointing to your JSON config:

```sh
pa11y --config ./pa11y.json http://nature.com/
```

If you're using the JavaScript interface, you can specify proxy settings like this:

```js
var options = {
    phantom: {
        parameters: {
            'proxy': '1.2.3.4:8080',
            'proxy-type': 'http|socks5|none',
            'proxy-auth': 'username:password'
        }
    }
};
pa11y(options, function (error, test, exit) {
    test('nature.com', function (error, results) {
        /* ... */
    });
});
```

Let me know if this works for you.

**Comment by rowanmanning** [comment]
I've added a question to the README which answers this as well: https://github.com/nature/pa11y#how-can-i-use-pa11y-with-a-proxy-server. Closing this issue, please reopen if you can't get it working.

**Comment by Malaber** [comment]
How would you do that nowadays? I want to use pa11y-dashboard but am stuck behind a corporate proxy. When i give my docker container the HTTP_PROXY vars also the mongodb requests go through the proxy, so that is also not really working.
