### ISSUE TITLE
Option to group results by type?

### ISSUE THREAD

**Issue by alexsoble** [nature/pa11y#89]
@rowanmanning -- What are your thoughts on an option to group results by type? For example, one subsection with Errors, another with Warnings, another with Notices. Might be useful for teams that want to prioritize their a11y work by tackling Errors first, then Warnings, then Notices.

**Comment by rowanmanning** [comment]
Hey Alex, I'm not sure whether this should be an option, or just an external reporter. You can currently kind of achieve this by using the `--ignore` flag:

```sh
pa11y --ignore "warning;notice" nature.com
```

If you feel like developing and publishing a new reporter that does this, I'd be happy to link to it from the [Reporters section of the README](https://github.com/nature/pa11y#reporters)

**Comment by qaDream77** [comment]
I'm actually working on something for this right now. I have pa11y provide me a json file which i parse into a formatted html report.

**Comment by alexsoble** [comment]
@rowanmanning: Makes sense, thanks for pointing out the `--ignore` option.

@qaDream77: Sounds interesting!

**Comment by mcrmfc** [comment]
I was thinking about making the error, warning, notice panels at the top of the html element filter results on click - what do you think?

**Comment by rowanmanning** [comment]
@mcrmfc: sure, feel free to open a PR
