### ISSUE TITLE
Question about phantom stdout messages

### ISSUE THREAD

**Issue by gianluca78** [nature/pa11y#93]
Hello! I'm using pa11y from command line to evaluate thousands of websites for a research. Everything is ok, your project is amazing. Thank you.

I need just a clarification. In some reports, I got messages like the following before the accessibility evaluation:

> phantom stdout: SyntaxError: Parse error
> phantom stdout: ReferenceError: Can't find variable: jQuery
> phantom stdout: ReferenceError: Can't find variable: init_news
> phantom stdout: TypeError: 'null' is not an object (evaluating 'div.autoscroll')

I suppose these are notice messages about errors in the assessed websites and that they not affect the accessibility evaluation. Am I right? Or it could be preferrable to exclude the reports with errors from the later analyses?

Thank you.

**Comment by rowanmanning** [comment]
Hi @gianluca78, glad you're enjoying using pa11y!

You're correct in assuming that these errors are client-side errors in the pages themselves, so I think it's fine to include them in your results as long as pa11y's not reporting 0 errors/notices/warnings for them – that would indicate that the page errors are interfering with pa11y.

**Comment by rowanmanning** [comment]
As a side note, if the research you're doing is ever made public we'd be really interested to see the results!

**Comment by gianluca78** [comment]
@rowanmanning thank you very much! I will inform you when (if :sweat_smile:) the research will be published...
