### ISSUE TITLE
Orphaned PhantomJS processes...

### ISSUE THREAD

**Issue by mcrmfc** [nature/pa11y#99]
Hi,

I don't mind looking into this but wanted to see whether there were any known issues around it first.

Essentially I have a simple script that iterates round a bunch of urls then calls the PA11Y Webservice api to create a task (if it doesn't exist) and then run it.

After the script finishes when I observe that every phantomjs process spawned during the run is still alive:

```pa11y     2043  7.0  2.6 1756820 103040 ?      Rl   11:45   1:09 phantomjs --ignore-ssl-errors=true --ssl-protocol=tlsv1 /usr/local/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/pa11y/node_modules/truffler/node_modules/phantom/shim.js 47875 127.0.0.1```

So I am guessing this may even be an issue with truffler, or possibly there is something about my environment that is causing this?

The pa11y log is clean and outputs exactly what I would expect e.g. 

```
Starting to run one-off task @ Tue Oct 20 2015 11:55:53 GMT+0100 (BST)
Starting task 56250d5ec9c3b18403276219
  > Injecting Pa11y (2202ms)
  > Running Pa11y on the page (5719ms)
  > PhantomJS page created for "http://www.foobar.co.uk/baz/"
  > Test running completed (20934ms)
  > Test function ran for "http://www.foobar.co.uk/baz/"
Finished task 56250d5cc9c3b18403276218
Finished running one-off task @ Tue Oct 20 2015 11:56:14 GMT+0100 (BST)
  > PhantomJS page for "http://www.foobar.co.uk/baz/" opened
  > Starting timeout timer
  > Injecting HTML CodeSniffer (1ms)
  > Injecting Pa11y (4116ms)
  > Running Pa11y on the page (5079ms)
  > Test running completed (22526ms)
  > Test function ran for "http://www.foobar.co.uk/baz/"
Finished task 56250d5ec9c3b18403276219
Finished running one-off task @ Tue Oct 20 2015 11:56:54 GMT+0100 (BST)
```

Let me know if there is any 'prior art' around this, if not I will keep digging.

Matt.

**Comment by rowanmanning** [comment]
Hi Matt,

Just wondering if you're using the most up-to-date version of the webservice (1.6.3 – released 4 days ago). This release specifically fixes the orphaned process issues.

If you _are_ using the latest version, I can look into it.

Rowan

**Comment by mcrmfc** [comment]
Rowan,

No i'm not - great will update now.

BTW - I have made a very rough and ready [chef cookbook](https://github.com/mcrmfc/chef-pa11y) for pa11y dashboard, so this is a good moment to see how that's handling upgrades!

Ok let's close this.

Cheers,

Matt.
